baseURL = "http://piafc.com/"
enableRobotsTXT = true
languageCode = "en-us"
title = "Pia Ferus-Comelo | Artist"
publishDir = "public"

[minify]
  minifyOutput = true
  
[markup.goldmark.renderer]
  unsafe= true

[params]
  email = "mailto:contact@piafc.com"
  instagram = "https://www.instagram.com/love_pia.fc/"