baseURL = "http://piafc.com/"
enableRobotsTXT = true
languageCode = "en-us"
title = "Pia Ferus-Comelo | Artist"
publishDir = "public"

[minify]
  minifyOutput = true
  
[markup.goldmark.renderer]
    unsafe= true
