baseURL = "http://piafc.com/"
enableRobotsTXT = true
languageCode = "en-us"
# TODO: change title
title = "Pia Ferus-Comelo"
publishDir = "public"

[minify]
  minifyOutput = true
  
[markup.goldmark.renderer]
    unsafe= true
